apiVersion: v1
kind: Service
metadata:
  name: {{ include "supernova.fullname" . }}
  labels:
{{ include "supernova.labels" . | indent 4 }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: supernova-mapping
      prefix: /supernova/
      service: {{ include "supernova.fullname" . }}:{{ .Values.service.port }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "supernova.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
